Bump lark-parser to latest version
starkware-libs/cairo-lang pull request #88
Opened 2022-08-08 14:05 UTC by RaitoBezarius

This closes #75 and uses the up-to-date package from PyPI (`lark-parser` seems to be abandoned from the author, who chose to rename its package to `lark`).

It also introduced a breakage change at version 1.0 where `standard` was renamed `basic`.

2022-09-05 16:44 UTC, RaitoBezarius commented
Friendly ping @liorgold2 ; I see you released 0.10.0, I think it is very important to move to `lark` :)

2022-09-05 22:13 UTC, liorgold2 reviewed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo-lang/88)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaitoBezarius)



<!-- Sent from Reviewable.io -->

2022-09-05 22:14 UTC, liorgold2 requested changes
Ok, we will try to merge it into 0.10.1.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo-lang/88#-:-NBEhvGL85jIfhk_beQu:b-a6jgdw)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaitoBezarius)



<!-- Sent from Reviewable.io -->

2022-09-05 22:23 UTC, RaitoBezarius commented
Rebased and fixed the conflicts @liorgold2

2022-09-06 09:50 UTC, liorgold2 requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo-lang/88)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaitoBezarius)



<!-- Sent from Reviewable.io -->

2022-09-06 09:50 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo-lang/88)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaitoBezarius)



<!-- Sent from Reviewable.io -->

2022-09-06 11:17 UTC, RaitoBezarius commented
@liorgold2 I'm not familiar with Reviewable, do you need me to change something in the PR?

2022-09-30 16:25 UTC, RaitoBezarius commented
Hey @liorgold2 ; can I get a look? :) Thanks!

2022-10-01 06:55 UTC, liorgold2 requested changes
> do you need me to change something in the PR?

No.

We are having a problem internally with the mechanism responsible for locking the package versions, which prevents me from getting forward with this PR. I'll try to bypass it so it can be merged in v0.10.1, but if I don't succeed, it'll probably have to wait to v0.10.2.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo-lang/88#-:-NDHIRpT85N8FIoyoSkt:bwqjg0s)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaitoBezarius)



<!-- Sent from Reviewable.io -->

2022-10-02 10:24 UTC, merged